enableGlobalCache: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.3.0.cjs
