enableGlobalCache: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

preferInteractive: true

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - arm64
    - x64

yarnPath: .yarn/releases/yarn-3.3.0.cjs
