enableGlobalCache: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

preferInteractive: true

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.4.1.cjs
