name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # this is a hack for @semantic-release/npm verifyConditions as it expects a package.json to exist already but we only generate it in the prepare step
      - run: |
          mkdir npm && echo '{ "name": "remember-promise" }' > npm/package.json
      - run: npx -p @semantic-release/changelog -p @semantic-release/exec -p @semantic-release/git -p semantic-release semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: deno publish
