name: Test
on:
  pull_request:

  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
            deno-version: v1.x
      - run: deno fmt
      - run: deno lint
      - run: deno test --coverage
      - run: deno coverage --lcov > coverage.lcov
      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage.lcov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
            deno-version: v1.x
      - run: deno run -A ./scripts/prepare_release.ts
